# Generated by Django 6.0.6 on 2026-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='chat_pdfs/'),
        ),
    ]
